"""add memo to favorites

Revision ID: 4802fc1e37f8
Revises: f4cb5a4d54fb
Create Date: 2026-05-20 15:45:53.454391

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4802fc1e37f8"
down_revision: str | Sequence[str] | None = "f4cb5a4d54fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorites", sa.Column("memo", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorites", "memo")
    # ### end Alembic commands ###
